#+BEGIN_COMMENT
.. title: 7 de Julio, 1932
.. slug: 7-de-julio-1932
.. date: 2022-08-19 23:33:02 UTC+01:00
.. tags: 
.. category: 
.. link: 
.. description: De lo épico individual a lo épico de masas
.. type: text

#+END_COMMENT


** La Revolución de Trujillo o De lo épico individual a lo épico de masas...

    —Y, cómo es que no os levantáis en armas, cuenta [[https://es.wikipedia.org/wiki/V%C3%ADctor_Ra%C3%BAl_Haya_de_la_Torre][Víctor Raúl]] que le increpó [[https://en.wikipedia.org/wiki/Julio_Antonio_Mella][Mella]], al oír su reporte de la situación nacional, el pasado reciente y su reciente estructural y también lo que sería su atalaya del período siguiente, siguiendo el formato de los reportes de situación que los jóvenes revolucionarios del mundo habían comenzado a adoptar a modo de organizarse. A Víctor Raúl, le hizo gracia la afrenta,
    {{{TEASER_END}}}
    de hecho sobre ello hilaría una tesis siguiente acerca de unos ciertos patrones de fenómeno, cuatro, sectores de penetración del ataque imperialista en América Latina que igualmente condicionaban o debía tenerse en cuenta al organizarse conjuntamente, como IndoAmérica, el antimperialismo. Y una doliente y jalonada batalla de ideas acerca de la acción inminente que conforme el tiempo ha ido dorando a partir de crónicas rotas por el exilio y viejas y nuevas discordias de método que de hecho han construído la sociología latinoamericana, conformaría el contexto. Esa mezcla de voces, la tertulia que atisba su luz tenue pero intensa por la oscuridad que rodea y cada quien con su memoria como bandera de abordaje en la trifulca de la marea los nuevos y viejos mapas de la situación mundial. Cualquier discusión podía ser preámbulo de epitafio. Y, todas las tardes después del trabajo habrían los talleres de la conspiración. Desde las secciones fundacionales que revisaban entre los jóvenes más conspicuos uno a uno los deberes de la inteligencia hasta callejuelas más sigzagueantes donde a sabiendas del pasado discutían los parámetros de los nuevos próceres. Una cuidadosa herrería del temple del guerrero para el caso muy concreto de verse expuesto al calabozo de la esquina o a la tortura de la cárcel militar.

La grandeza de espíritu del hombre corriente era el mundo posible que empezaba en el silencio de los círculos de nadie de la discusión y que esperaba su momento en una historia que le era ajena sin esperanza. Hacía terreno en la afinación de la definición de los asuntos, y el sueño del rehacer lo roto era el territorio donde se oía el ruido de sable de las grandes batallas. La tragedia, de hecho perfilaba al personaje por sus creencias y sus acuerdos o sus discrepancias en los diagnósticos como ninguna discusión en la historia de las discusiones habría influído jamás en los hechos, en el sabor del pan, mojado en aceite y azúcar la ensalada de verduras, el pescado frito cualquier tarde en casa. Eso eran los espejos negros de los años 30 en las afueras medio ciudades todavía coloniales, medio latifundios, del Perú de entonces. Con una guerra mundial sangrienta, ya cocida, aunque los recortes de la prensa en el album de mi abuelo no eran todavía amarillentos como cuando los vi por primera vez, y sin embargo ya estábamos en la euforia de otra que aún hervía lo terrible. Un coro universal venturreaba de fondo las letras de una batalla final, quizá clase contra clase, quizá un frente de oprimidos. No una clase, quizá todas las clases explotadas. Y todos, todos contra el enemigo, ese pasado vergonzante de pobreza y olvido.

    El lego crítico, sin embargo crítico y sin embargo lego observaría la crónica sin tener palabras, entiendo el conflicto —diría. Y, quién sostiene al tirano. A quién disparar esas armas. Muchos años después, digamos por ejemplo 30 años después, porque queriendo ser punto final de todas las insurrecciones del pasado fue también la madre de todas las insurrecciones que siguieron, ese otro lado de la cuestión vuelve a plantear su booleana querella. Póngase de elemento de juicio digamos el anónimo soldado que dispara anónimo, cobra su jornal y vuelve a casa con su jornal. Porque imaginar, por ejemplo a [[https://en.wikipedia.org/wiki/Javier_Heraud][Heraud]], querer hacer blanco en un soldado anónimo. Cómo cantar la sociología de esa tragedia. Ese escenario, un río de aguas tranquilas y canoas y bosques, que ve la muerte simplemente, venir simplemente. No hay poema que recoga la camisa machada de sangre y conviertan la ignorancia en escombros y construyera la grandeza de esa patria grande. Diariamente. Por ese túnel del tiempo se ha construído desde entonces la distopía de que esa madrugada del [[https://es.wikipedia.org/wiki/Revoluci%C3%B3n_de_Trujillo_de_1932][7 de Julio]] nunca sucedió.
    Y todas las mañanas el rezo diario, que la injusticia me sea indiferente, que la injusticia no me pise a mí ni a los míos hoy, diariamente. Y un largo exilio interior y clandestinidad que rompió el país en tantos exilios y apartheid. Ese gran gueto de blancos de no querer ser cholos y todos los demás ensayando explicaciones al problema del indio, incluso a veces el indio. Y amurallar la marea interior con catacumbas. Y el recuerdo de los que fueron seis mil y pico muertos. Los fusilados en Chan Chan. Las fosas comunes a pie de carretera.

—Pero, tiene el crítico derecho a no entender lo épico?. La historia del país era la crónica de un país de anónimos. Y el abuso era una herida abierta diaria, desde el amanacer al amanecer. Tenía mando el gamonal incluso fuera del fundo y el cacique no sólo en el cacicazgo. Hay ahora ciencias sociales, derecho internacional, acuerdos bilaterales y organismos internacionales de regulación y convención incluso no-vinculante, o por cierto no necesariamente vinculante, pero que deja señas, la base jurídica de lo que podría llegar a ser una acción de masas, no es acaso la acción colectiva, el objeto, puestos a convenir en una logística de la acción colectiva?. Aquí lo épico sería el todos a una de la acción social, lo épico de masas, el todos a una.

Entonces solo estaba el gamonal. Luego todos los demás incluyendo sus servidores públicos. Pinga, palo y caridad. Eso sí, misa los domingos, guantes blancos y velo tul, solo tenéis que mirar las fotos, las finas estampas remedando pretensiones de señorío español en los callejones de un solo caño.

    Y así pasaron día a día los largos años de clandestinidad, y apartheid. Libros metidos en cajas secretas en zulos, debajo de la cama, detrás de la pared y que nadie debía saber que leías. Y un país lleno de soplones conteniendo la marea de un sueño y una traición. Que, fueron 9000 muertos, hubo bombardeos a civiles, dinero público, arsenal militar utilizado para zanjar violentamente contra disidentes de gobiernos ilegales, e imponer la sumisión y el olvido. Y el recuerdo de los recuerdos. 
    Sí, aquí podría agregarse que Víctor Raúl, hablaba a una consciencia nacional lo decía muchas veces y se refería a una reinvindicación mayor. En los términos que tuvo en su momento se refería al acto humano de construir civilización y donde la reivindación de lo nacional era simplemente una eventualidad telúrica, la conexión que establecemos con el entorno pero la reinvindicación clave era la consciencia en sí, una ontología en una etología. Un hombre nacido en la tierra, en estas tierras que organiza comunidad, monta caminos, lleva el agua de un sitio de cosecha a otro, electrifica la montaña, convierte el desierto, se cubre del frío en las zonas de cordillera, siembra, cosecha, atendiendo a las diferencias estacionales, y del terreno y almacena alimentos y distribuye de acuerdo a cierta particular logística. Cuenta cuántos somos, enseña a contar y que a nadie le falte. Y que cuenten todos que cuentan todos. Durante años y años sin embargo hubo algo que ocultar. Algo de lo que hablar en pequeños círculos. Una memoria de la que era mejor no hablar. Alguien tendría que hablar a los demás y que aparte del plan máximo y el plan mínimo, el plan fuere más que un discurso al guerrero que es capaz de comerse la lista de compañeros o el mapa del polvorín. Luis Alberto Sánchez tuvo unas palabras, muchas palabras, demasiadas palabras para ello en los escritos de sus últimos días. Echaba de menos la preparación de los militantes, o el viejo asunto de los cuadros, en un momento en que merodeando la posibilidad de gobernar. Un comando con la comisión del plan de gobierno echa de menos la preparación de sus cuadros, ciertamente. Economistas, ingenieros pesqueros, de caminos, civiles, agro-industriales, etc. Un partido ideal en los términos de la ley electoral del momento. Un ente ideal que se ajuste a ley. Y vuelta el dilema de lo épico, una organización partidaria que tras 60 años, a la fecha de los escritos de Sánchez de sus últimos días, se ocupa en apretar las tuercas de un plan de gobierno probable, de allí las prisas, que no habría sido posible sin la resistencia espartaquista de los miles de militantes que eran capaces de comerse los padrones y los mapas del polvorín antes que disuadirse. El ideal de partido ideal y lo épico. Teníamos que educar la necesidad de tener derecho a tener derecho. Construir un estado, un sistema de gestión y sobre todo mirar la economía como una ingeniería de los recursos no una tabla que marcase la tasa de ganancia en esos cálculos del capital que sólo arrastran las usanzas de Wall Street y ejecutan esos nuevos y viejos Chicago boys, capaces de desconectar el valor de uso del valor de cambio si acaso resulta que la tasa de ganancia oscilara nerviosamente, no viene acaso del hambre la ingeniería más eficiente, la propia ingeniería no viene del hambre?

    Sí, que —Aunque la nueva forma de organizar sociedad tuviera que minimizarse y actuar com embrión en gesta dentro de la sociedad caduca y hablar de sus muertos en secreto. Qué derecho tendría una secta de fanáticos de hablar por los demás. Dirían, decían, dicen. Aunque nosotros, la secta de fanáticos, sabemos ciertamente que habla el miedo, sí. El viejo tenía razón me soltó sin venir a cuento mi abuelo en su rincón. El epifenómeno de sociedad política donde las fuerzas armadas guardan el latifundio y cuidan al oligarca es un escenario. Las pequeñas gendarmerías donde el conciliábulo espartaquista puede, porque puede, preguntar en voz alta  —Y por qué no os levantáis en armas, es otro.
    —Abuelo..

    Y la necesidad de la libertad bulle de pronto como una una catarata diáfana. Aquí, nunca fue así. Aquí el fenómeno de la sociedad organizada no ha sido nunca el punto de llegada. Aquí la sociedad organizada es una institucionalización organizada, una gran galera.
    —Abuelo, para...

    Una imposición a sable y látigo. Una gran prisión bajo el comando conjunto de las fuerzas armadas. Jamás un contrato social, lo que es un acuerdo de masas, sino una camisa de fuerza, una estructura mounstruo que apisona fuerte. Y, aquí habla el miedo. Y el miedo hace inclinar cabezas, hace decir —Sí, señor. Mirar para otro lado, hablar bajito. Justificar al patrón, ser el ladrido del perro del hortelano. Si dabas pistas que llevaran a detener a un aprista, en compensación podías saltar en la cola y la compañía telefónica te instale teléfono en casa, según cuenta la crónica del barrio. De modo que para tener espíritu democrático había guardar silencio ante la humillación.
    —Aún así, el peruano no es un caso particular. El miedo tiene muchas caras y muchas lenguas...

    Un hecho extraño donde los halla describe esta experiencia de crecimiento democrático, o lo que fuere. —Salude Ud al general [[https://es.wikipedia.org/wiki/Manuel_Odr%C3%ADa][Odría]] le dice Víctor Raúl al hijo de Negreiros, el líder sindicalista acribillado de 28 disparos a quemarropa en las esquina de Petit Thouars y 28 de Julio. —28 de Julio, nada menos, por los esbirros bajo las órdenes del ministro Esparza, el Cayo Mierda o Bermúdez del panfleto del escritor que luego recibió un Nobel. —Salude Ud al general Odría. La lección democrática aquí es la respuesta del joven. —El joven nervioso obedeció en silencio, esa sería la respuesta del joven y esa es toda la lección democrática, obedecer en silencio al líder intermediador. Porque secundar al lider intermediador por el hecho de que el líder intermediador sea quien es vuelve a situar el incidente en lo épico, en la trama que tuviere entre manos el jefe del partido en el contexto del plan que tuviere entre manos el jefe del partido. El extracto pedagógico en cambio es el silencio y la humillación ante el intermediador que intermedia el poder y el ciudadano. Luego está el relato, el victimario y el hijo de la víctima en una intermediación educadora de masas o cuanto menos controversial. Y eximir de toda culpa al tirano, ahora aliado, Odría. Pero puede entenderse el compromiso político sin el carbón de lo épico o podría una comunidad zanjar territorio que pudiere elevar a recurso de ética o jurisprudencia de lesa humanidad en el ejercicio del poder o el ejercicio de la polémica del ejercicio del poder?. El recuerdo de la madrugada del 7 de Julio guarda como espíritu en pena que una respuesta nuestra la saque de las sombras, el submundo donde habita y nos devuelva el poder de construir y reconstruir la base jurídica y lo épico vuelva del individuo a las masas.
