#+BEGIN_COMMENT
.. title: A Py Scratch Sheet On The Fly ~~`
.. slug: a-py-scratch-sheet-on-the-fly
.. date: 2021-02-17 18:54:14 UTC
.. tags: 
.. category: 
.. link: 
.. description: 
.. type: text

#+END_COMMENT

Hi, People.
Os presento aquí una ventana de ayuda y probar al vuelo trocetes de código (python). Útil si requerís verificar algo (corto y) rápido, un manual que estéis leyendo, por ejemplo, y os pilla en el trayecto del metro o, en fin, fuera del entorno habitual de estudio o trabajo y/o no podéis esperar. —Hey, que a veces pasa...

{{{TEASER_END}}}

#+begin_export html
<html>
  <!DOCTYPE html>
  <meta charset="utf-8">
  <head>
      <link rel="stylesheet" type="text/css" href="https://storage.googleapis.com/app.klipse.tech/css/codemirror.css">

      <script>
       window.klipse_settings = {
         selector_eval_python_client: '.language-klipse-python'
       };
      </script>

  </head>

  <body>
    <div>
       <p>Por cierto, powered by <strong>klipsify</strong> es interactiva, probad!</p>
        <p>And now, we are going to <strong>klipsify</strong> this code snippet:</p>

        <pre><code class="language-klipse-python">
def foo():
    print("Hello World!")

foo()
        </code></pre>
    </div>
    <script src="https://storage.googleapis.com/app.klipse.tech/plugin_prod/js/klipse_plugin.min.js?v=7.3.4"></script>
  </body>

</html>

#+end_export

* Edit. date ;; Wed 21 Sep 19:42:50 BST 2022 
I should say that the above python scratch page has a handicap as it cannot run properly on mobile browsers, but the fact is that this try dates back to a time when PyScript did not exist, yet. Let's try the same plan with this other approach this time, using [[https://pyscript.net/][PyScript]].

#+begin_export html
<!DOCTYPE html>
<html lang="en">
    <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />

    <title>REPL</title>

    <link rel="icon" type="image/png" href="favicon.png" />
    <link rel="stylesheet" href="https://pyscript.net/alpha/pyscript_base.css" />
    <script defer src="https://pyscript.net/alpha/pyscript.js"></script>
    <py-env>
      - numpy
    </py-env>
    </head>
    <body>
      <div id="output" class="text-3xl"></div>
      <!-- <py-script>
        
      </py-script> -->
      <py-repl></py-repl>
    </body>

</html>
#+end_export
